---
# tasks file for wordpress
- name: install wordpress package
  apt:
    name: wordpress, php, libapache2-mod-php, php-mysql
    state: present
    update_cache: yes
- name: copy wordpress.conf file
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf
  notify:
  - restart apache2 service
- name: enable wordpress site
  file:
    src: /etc/apache2/sites-available/wordpress.conf
    dest: /etc/apache2/sites-enabled/wordpress.conf
    state: link
  notify:
  - restart apache2 service
- name: enable rewrite module
  file:
    src: /etc/apache2/mods-available/rewrite.load
    dest: /etc/apache2/mods-enabled/rewrite.load
    state: link
  notify:
  - restart apache2 service
- name: start service
  service:
    name: apache2
    enabled: yes
    state: started


